// Code generated by MockGen. DO NOT EDIT.
// Source: first-api/internal/usecases (interfaces: OrderRepository,ProductRepositoryForOrder)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/mocks/repository.go first-api/internal/usecases OrderRepository,ProductRepositoryForOrder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "first-api/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderRepository) CancelOrder(arg0 context.Context, arg1 *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderRepositoryMockRecorder) CancelOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderRepository)(nil).CancelOrder), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(arg0 context.Context, arg1 *model.Order) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), arg0, arg1)
}

// GetOrderByID mocks base method.
func (m *MockOrderRepository) GetOrderByID(arg0 context.Context, arg1, arg2 string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderByID), arg0, arg1, arg2)
}

// GetOrders mocks base method.
func (m *MockOrderRepository) GetOrders(arg0 context.Context, arg1, arg2 int, arg3 string) (*[]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*[]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderRepositoryMockRecorder) GetOrders(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetOrders), arg0, arg1, arg2, arg3)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepository) UpdateOrderStatus(arg0 context.Context, arg1 *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderStatus), arg0, arg1)
}

// MockProductRepositoryForOrder is a mock of ProductRepositoryForOrder interface.
type MockProductRepositoryForOrder struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryForOrderMockRecorder
	isgomock struct{}
}

// MockProductRepositoryForOrderMockRecorder is the mock recorder for MockProductRepositoryForOrder.
type MockProductRepositoryForOrderMockRecorder struct {
	mock *MockProductRepositoryForOrder
}

// NewMockProductRepositoryForOrder creates a new mock instance.
func NewMockProductRepositoryForOrder(ctrl *gomock.Controller) *MockProductRepositoryForOrder {
	mock := &MockProductRepositoryForOrder{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryForOrderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepositoryForOrder) EXPECT() *MockProductRepositoryForOrderMockRecorder {
	return m.recorder
}

// GetProductInfo mocks base method.
func (m *MockProductRepositoryForOrder) GetProductInfo(arg0 context.Context, arg1 []model.NewOrderItemDTO) (*model.ProductInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductInfo", arg0, arg1)
	ret0, _ := ret[0].(*model.ProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductInfo indicates an expected call of GetProductInfo.
func (mr *MockProductRepositoryForOrderMockRecorder) GetProductInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductInfo", reflect.TypeOf((*MockProductRepositoryForOrder)(nil).GetProductInfo), arg0, arg1)
}
